### ISSUE TITLE
关于计算比率类指标的兼容性问题

### ISSUE THREAD

**Issue by mjn96** [lizeyan/Squeeze#20]
你好，论文中有提到Squeeze算法对与成功率、点击率等比率类指标是支持的。在理论推导中也没有矛盾之处。

但是关于代码执行层面我有一点疑问。在Squeeze项目的[squeeze.py](https://github.com/NetManAIOps/Squeeze/blob/master/squeeze/squeeze.py)的第162行开始的_root_cause_score这个函数，以及在PSqueeze项目中的[squeeze.py](https://github.com/NetManAIOps/PSqueeze/blob/master/squeeze/squeeze.py)的第275行开始的ps这个函数里，计算_a1,_a2。用的都是对S下sum(real_value)/sum(predict_value)*predict_value。但是sum(real_value)/sum(predict_value)并不是S下的观测指标的真实变化情况。这个似乎只适用于可加和的基础类指标。
![image](https://github.com/NetManAIOps/Squeeze/assets/48405405/db0614f4-993b-4631-a865-431a3bfe2d80)
是不是现阶段的这个开源代码对于比率类的指标并不是兼容的？

**Comment by lizeyan** [comment]
https://github.com/NetManAIOps/PSqueeze
可以看下这个仓库里面的代码。我有点忘了这里具体是什么情况，但这个版本的代码确实有一些bug

**Comment by mjn96** [comment]
感谢大佬及时回复，这两个代码仓库我都看了，实践中我也用的是PSqueeze跑的，但是发现跑出来的f(S)和v(S)是不符合预期的，PSqueeze的[squeeze.py](https://github.com/NetManAIOps/PSqueeze/blob/master/squeeze/squeeze.py)的第277行
```python
_pv, _pf = np.sum(_v1), np.sum(data_p.predict.values)
```
疑似是Squeeze项目里没有修改掉的代码，我们发现_pv, _pf和
```python
reduced_data_p, _ = self.get_derived_dataframe(
    frozenset(elements[:partition]), cuboid=cuboid,
    reduction="sum", return_complement=True,
    subset_indices=np.concatenate([indices, self.normal_indices]))
```
得到reduced_data_p的real和predict其实值是一样的，reduced_data_p的结果应该就是对原始数据中S下的predict和real的加和，这个好像在分析比率类指标根因的时候是不合理的。

**Comment by lizeyan** [comment]
我看了一下，在PSqueeze的代码里_pv和_pf都没有使用了，这个应该确实是错的，所以在PSqueeze里面改成用reduced_data_p了。
然后在`get_derived_dataframe`里面，我看确实是先聚合再算除法（或者其他op）的，感觉应该是合理的 
```
_values = self.op(*[reduce(_data[["real", "predict"]].values) for _data in _data_list])
```
你可以构造一个样本数据直接测试一下get_derived_dataframe得到的结果是不是符合预期的

**Comment by mjn96** [comment]
我这边拿真实数据做了测试，代码的执行结果和真实结果存在一些差异。
我理解这块是不是得从__init__下就开始改造，对与衍生类的指标，需要在原始的data里把计算出real和predit的可加和的基础类指标也加入进去，然后在修正get_derived_dataframe里关于衍生类指标的支持。

**Comment by lizeyan** [comment]
data_list里面就是可加和的基础类指标
https://github.com/NetManAIOps/PSqueeze/blob/94239f95b3df4748a410b7dc6eac9afb261afbd1/run_algorithm.py#L219C9-L223C10
在这里可以看到，在衍生指标的实验里，传给Squeeze的就是两个基础指标
```
        model = get_model_psq(
            [dfa, dfb], op=divide,
            debug=debug, output_path=output_path, timestamp=timestamp, derived=True,
            **kwargs
        )
```

**Comment by mjn96** [comment]
所以对于a/b类型的指标，就是把a的real和predict存在dfa，把b的real和predict存在dfb，传入两个df然后定义相关的op去计算是吗？
